name: Elevator Images 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: checkout 
         uses: actions/checkout@main
         
       - name: install
         run: yarn
         
       - name: build project
         run: yarn build
       - name: Build the Docker image
         run: |
           docker login --username=${{ secrets.DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}
           docker build -t elevator:latest . 
           docker tag elevator registry.cn-hangzhou.aliyuncs.com/elevator-hub/elevator:latest
           docker push registry.cn-hangzhou.aliyuncs.com/elevator-hub/elevator:latest
      
       - name: ssh docker login
         uses: appleboy/ssh-action@master
         with: 
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: cd /usr/app/elevator/ && sh docker.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
